* MELLON
Pythonis kirjutatud steganograafia programm. Lubab mitut faili korraga (de)kodeerida.

** Vajalikud teegid
- =bitarray= - bititaseme manipulatsioonid
- =pillow= - pildifailide muutmine
- =PySimpleGUI= - kasutajaliides

** Kasutamine
1. Installi vajalikud teegid
2. Jooksuta =src/mellon.py= fail.
3. Vali kas soovid kodeerida või dekodeerida.
4. Kodeerimisel vali vajalikud failid ja vajuta nuppu =Kodeeri=.
5. Dekodeerimisel vali vajalikud failid ja vajuta nuppu =Dekodeeri=. Pane saladuse uue nime lõppu kindlasti =.zip.bz2=,
   see on formaat, millena saladused salvestatakse ja lisades selle failinime lõppu tunneb operatsioonisüsteem kohe ära,
   mis failiga tegemist on.

** Tehniline info

*** Kodeerimise protsess

Saladus - fail, mis kodeeritakse
Seif - fail, millesse kodeeritakse

**** DONE Kui antakse mitu salajast faili, luuakse neist kõigepealt arhiiv, mis kodeeritakse seifi(desse).
**** DONE Enne kodeerimist kontrollitakse, kas saladus mahub seifi, antakse kasutajale teada.
**** DONE Enne saladuse kodeerimist kodeeritakse päis.
**** DONE Kodeeritakse saladus, 1 bait ühes pikslis. 2 bitti punases kanalis, 3 bitti rohelises ja sinises.
**** DONE Mitme seif-faili korral tükeldatakse saladus enne kodeerimist.

*** Päise formaat

| Kirjeldus            | Pikkus  |
|----------------------+---------|
| Faili kontrollsumma  | 2 baiti |
| Ploki järjenumber    | 1 bait  |
| Plokkide arv         | 1 bait  |
| Pikkus               | 4 baiti |

Terve päis võtab 8 baiti

** Kasutajaliides

*** DONE Failide valimine
*** DONE kodeerimis-errorite näitamine GUIs

** Programmi töö

1. Kasutaja valib kas kodeerida või dekodeerida.
2. Kasutaja valib failid, mida (de)kodeerida.
3. Kasutaja valib sihtkoha, kuhu faili (de)kodeerida.
4. Teeme ära mis vaja
