* MELLON
Pythonis kirjutatud steganograafia programm.

** Vajalikud teegid
- =bitarray= - bititaseme manipulatsioonid
- =pillow= - pildifailide muutmine

** Kasutamine
#+BEGIN_SRC shell
usage: mellon.py [-h] salajane_fail sisend_pilt väljund_pilt

positional arguments:
  salajane_fail  salajane fail, mille sisu peidetakse pilti
  sisend_pilt    pilt, millesse peidetakse info
  väljund_pilt   uus nimi, millena infot sisaldav pilt salvestatakse

options:
  -h, --help     show this help message and exit
#+END_SRC

** Projekti progress
*** DONE Naiivne kodeerimine/dekodeerimine
*** DONE PNG failid
*** TODO Targem/efektiivsem algoritm
*** TODO JPEG failid

** Ploki kaupa kodeerimine

*** Ploki päis
| Suurus  | Kirjeldus             |
|---------+-----------------------|
| 1 bait  | MELLON allkiri        |
| 1 bait  | Faili number          |
| 1 bait  | Plokkide arv failis   |
| 1 bait  | Ploki järjenumber     |
| 4 baiti | Ploki pikkus baitides |

Terve päis võtab kokku 8 baiti ehk 64 bitti.

Ühe ploki sisse mahub maksimaalselt 4 gigabaiti, ühe faili kohta saab olla maksimaalselt 255 plokki,
seega maksimaalne failisuurus on ligi 1.1 terabaiti, mis on igaks realistlikuks juhtumiks piisav.

Päisele järgneb ploki sisu.

*** Baitide ühildamine
X - kas 0 või 1
0 - 0 bitt
1 - 1 bitt

Salajase baidi formaat - 111111XX
Algse baidi formaat    - XXXXXXXX
& operatsioon nende liitmiseks
