* MELLON
Pythonis kirjutatud steganograafia programm.

** Vajalikud teegid
- =bitarray= - bititaseme manipulatsioonid
- =pillow= - pildifailide muutmine

** Kodeerimine

*** Kodeerimise protsess

Saladus - fail, mis kodeeritakse
Seif - fail, millesse kodeeritakse

**** TODO Kui antakse mitu salajast faili, luuakse neist kõigepealt arhiiv, mis kodeeritakse seifi(desse).
**** TODO Enne kodeerimist kontrollitakse, kas saladus mahub seifi, antakse kasutajale teada.
**** TODO Enne saladuse kodeerimist kodeeritakse päis.
**** TODO Kodeeritakse saladus, 1 bait ühes pikslis. 2 bitti punases kanalis, 3 bitti rohelises ja sinises.
**** TODO Mitme seif-faili korral tükeldatakse saladus enne kodeerimist.

*** Päise formaat

| Kirjeldus            | Pikkus  |
|----------------------+---------|
| Faili kontrollsumma  | 2 baiti |
| Ploki järjenumber    | 1 bait  |
| Plokkide arv         | 1 bait  |
| Pikkus               | 4 baiti |

Terve päis võtab 8 baiti

*** Baitide ühildamine
- X - kas 0 või 1
- 0 - 0 bitt
- 1 - 1 bitt

Salajase baidi formaat - 111111XX
Algse baidi formaat    - XXXXXXXX
& operatsioon nende liitmiseks
